package com.venovu.energiklart;

import android.os.Bundle;
import android.os.Environment;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.Button;

import com.itextpdf.text.Anchor;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chapter;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Font;
import com.itextpdf.text.List;
import com.itextpdf.text.ListItem;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Section;
import com.itextpdf.text.pdf.PdfWriter;

import java.io.FileOutputStream;
import java.util.Date;

/**
 * Created by Laney47 on 2016-03-30.
 */
public class PdfCreator extends AppCompatActivity{
    private static String FILE = "FirstPdf.pdf";
    private static Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18,
            Font.BOLD);
    private static Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.NORMAL, BaseColor.RED);
    private static Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16,
            Font.BOLD);
    private static Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12,
            Font.BOLD);

    private String number= "50";
    private long idHouse=50;
    private String street="asdasdasd";
    private String city="asdasdasd";
    private String zip="asdasdasd";
    //  private java.util.List<Room> mListRooms=SingeltonList.getInstance().getList();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        /*Button swosh = (Button)findViewById(R.id.pdfButton);
        swosh.setOnClickListener(
                new Button.OnClickListener() {
                    public void onClick(View v) {
                        createPDF();



                    }
                }

        );
    }*/
    }

    public void createPDF(){

        try {
            String outpath= Environment.getExternalStorageDirectory().getAbsolutePath()+"/Adress_"+"Duja" + ".pdf";
            System.out.println( "HERE IS THE LINK: " + outpath);
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(outpath));
            //PdfWriter.getInstance(document, new FileOutputStream(FILE));
            document.open();
            addMetaData(document);
            addTitlePage(document);
            addContent(document);
            document.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    private  void addMetaData(Document document) {
        document.addTitle("My first PDF");
        document.addSubject("Using iText");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("asd");
        document.addCreator("asd");
    }
    private  void addTitlePage(Document document)
            throws DocumentException {

        Paragraph preface = new Paragraph();
        // We add one empty line
        addEmptyLine(preface, 1);
        // Lets write a big header
        preface.add(new Paragraph("STATUS REPORT", catFont));

        addEmptyLine(preface, 1);
        // Will create: Report generated by: _name, _date
        preface.add(new Paragraph("Report generated by Group 1" + ", " + new Date(), //$NON-NLS-1$ //$NON-NLS-2$ //$NON-NLS-3$
                smallBold));
        addEmptyLine(preface, 3);
        preface.add(new Paragraph("House informations:",
                smallBold));

        addEmptyLine(preface, 3);

        preface.add(new Paragraph("House's adress: Street " + street + ", No: " + number,
                smallBold));
        addEmptyLine(preface, 1);

        preface.add(new Paragraph("City: " + city,
                smallBold));
        addEmptyLine(preface, 1);

        preface.add(new Paragraph("Zip code: " + zip,
                smallBold));

        addEmptyLine(preface, 1);

        document.add(preface);

        // Start a new page
        document.newPage();
    }
    private  void addContent(Document document) throws DocumentException {
        Anchor anchor = new Anchor("First Chapter", catFont);
        anchor.setName("List of rooms:");

        // Second parameter is the number of the chapter
        Chapter catPart = new Chapter(new Paragraph(anchor), 1);


        //  for(int i=0;i<mListRooms.size();i++) {

        Paragraph subPara = new Paragraph("Room:", subFont);
        Section subCatPart = catPart.addSection(subPara);
        subCatPart.add(new Paragraph("Time: "));
        subCatPart.add(new Paragraph("Humidity: "));
        subCatPart.add(new Paragraph("Light: "));
        subCatPart.add(new Paragraph("Temperature: "));
        subCatPart.add(new Paragraph("Noise: "));
        // add a list

        //  }


        // now add all this to the document
        document.add(catPart);

    }

    private static void createList(Section subCatPart) {
        List list = new List(true, false, 10);
        list.add(new ListItem("First point"));
        list.add(new ListItem("Second point"));
        list.add(new ListItem("Third point"));
        subCatPart.add(list);
    }

    private static void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }
}
